
version: '3.8'

services:
  skaidex-robotics:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: skaidex-robotics-app
